// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqN3ERyZHDGnuy2vPOe7uJ8jom_cyS-Hs',
    appId: '1:199241027327:web:ebb6075e7cb0c2577586ca',
    messagingSenderId: '199241027327',
    projectId: 'social-circle-7368b',
    authDomain: 'social-circle-7368b.firebaseapp.com',
    storageBucket: 'social-circle-7368b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUc8q1CVmeiOVAWXxGJbmMT98OWS_eROo',
    appId: '1:199241027327:android:157181328b0452bb7586ca',
    messagingSenderId: '199241027327',
    projectId: 'social-circle-7368b',
    storageBucket: 'social-circle-7368b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUM5jQ7SjB31f04OLrsJbFpd97aZZfQPQ',
    appId: '1:199241027327:ios:f95dd0cb6bc0fcff7586ca',
    messagingSenderId: '199241027327',
    projectId: 'social-circle-7368b',
    storageBucket: 'social-circle-7368b.appspot.com',
    iosClientId: '199241027327-opme3v1h5k0qctq1emqieegji3s69eht.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUM5jQ7SjB31f04OLrsJbFpd97aZZfQPQ',
    appId: '1:199241027327:ios:ff641be3fe2c32b67586ca',
    messagingSenderId: '199241027327',
    projectId: 'social-circle-7368b',
    storageBucket: 'social-circle-7368b.appspot.com',
    iosClientId: '199241027327-t7vc69mkmi8pq7tkrm144mbg8t5ivqee.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattr.RunnerTests',
  );
}
